version: "1.0"
info:
  model: int-scaffold
packages:
- name: Man_lakr_25febProject
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
- name: SalesforceSoapTest1015
  gitServerName: Karthik
  gitUrl: https://github.com/lakshmidevi277
  gitUsername: karthikbm
  gitBranch: main
