version: "1.0"
info:
  model: int-scaffold
packages:
- name: Man_lakr_25febProject
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
- name: SalesforceSoapTest1015
  version: "1.0"
  gitServerName: Karthik
  gitUrl: https://github.com/lakshmidevi277
  gitUsername: karthikbm
  gitBranch: main
- name: WmSalesforceProvider
  version: 10.7.0.0.53
services:
- serviceName: project.man_lakr_25feb.integrations:sf_tap
  packages:
  - name: Man_lakr_25febProject
    version: "1.0"
  - name: SalesforceSoapTest1015
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.187
- serviceName: project.man_lakr_25feb.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.operations.actions:basic_acc
  packages:
  - name: Man_lakr_25febProject
    version: "1.0"
  - name: SalesforceSoapTest1015
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.187
configurationVariables:
  ? iscloudstreamsconnectorservice.project..man_lakr_25feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:basic_acc.connectionAlias
  : Connections:sf_basic_1015
  ? iscloudstreamsconnectorservice.project..man_lakr_25feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:basic_acc.virtualServiceName
  : WmCloudStreams.SoapVS
